const defaultTheme = {
  PRIMARY_BACKGROUND_COLOR: '#FFFFFF',
  PRIMARY_TEXT_COLOR: '#121212',
  SECONDARY_TEXT_COLOR: '#333333',
  THIRD_TEXT_COLOR: '#CCCCCC',
  ACTIVE_TEXT_COLOR: '#121212',
  INACTIVE_TEXT_COLOR: '#999999',
};

export default {defaultTheme};
